import { useState, useEffect, createContext, useContext, type ReactNode } from "react";

export type Language = "de" | "fr" | "it" | "en" | "es";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translation keys for the application
const translations = {
  de: {
    // Navigation
    "nav.login": "Anmelden",
    "nav.getStarted": "Jetzt starten",
    "nav.logout": "Abmelden",
    
    // Landing page
    "landing.hero.title": "Nachmieter finden",
    "landing.hero.subtitle": "leicht gemacht",
    "landing.hero.description": "Die erste Schweizer Plattform, die den schmerzhaften Nachmieter-Prozess in einen einfachen, automatisierten Ablauf verwandelt. Für alle drei Parteien.",
    "landing.stats.clicks": "Klicks zum Publizieren",
    "landing.stats.application": "Min. Bewerbung",
    "landing.stats.acceptance": "Regie-Akzeptanz",
    "landing.cta.listProperty": "Wohnung inserieren",
    "landing.cta.findProperty": "Wohnung finden",
    "landing.trust.noCreditCard": "Keine Kreditkarte erforderlich",
    "landing.trust.readyToUse": "Sofort einsatzbereit",
    "landing.card.dossierValidated.title": "Dossier validiert",
    "landing.card.dossierValidated.description": "Bereit für Regie-Einreichung",
    "landing.howItWorks.title": "So einfach funktioniert's",
    "landing.howItWorks.description": "Von der ersten Veröffentlichung bis zur finalen Regie-Einreichung – alles automatisiert und rechtssicher.",
    "landing.howItWorks.step1.title": "Smart Link erstellen",
    "landing.howItWorks.step1.description": "Mietvertrag hochladen oder manuell eingeben. AI extrahiert automatisch alle wichtigen Daten.",
    "landing.howItWorks.step2.title": "Dokumente sammeln",
    "landing.howItWorks.step2.description": "Interessenten laden einmalig ihre Dokumente hoch. AI validiert und klassifiziert automatisch.",
    "landing.howItWorks.step3.title": "Besichtigungen planen",
    "landing.howItWorks.step3.description": "Automatische Terminbuchung ohne Doppelbelegungen. Calendly-Integration für nahtlose Planung.",
    "landing.howItWorks.step4.title": "Top-3 Dossier",
    "landing.howItWorks.step4.description": "Die besten 3 Kandidaten werden automatisch als PDF/ZIP für die Regie zusammengestellt.",
    "landing.features.title": "Alle Features auf einen Blick",
    "landing.features.description": "Entwickelt für die Schweizer Rechtslandschaft und lokale Bedürfnisse",
    "landing.features.parser.title": "AI Mietvertrag-Parser",
    "landing.features.parser.description": "Lädt Ihren Mietvertrag hoch und extrahiert automatisch Miete, Kündigungsfrist, Schlüsselanzahl und erstellt eine Aufgabenliste.",
    "landing.features.parser.badge": "Unterstützt alle 5 Sprachen",
    "landing.features.documentWizard.title": "Dokument-Wizard",
    "landing.features.documentWizard.description": "Einmalig Dokumente hochladen, AI validiert sofort. Direkte Kantonsportal-Links für Betreibungsauszug.",
    "landing.features.documentWizard.badge": "Schweizer Datenschutz",
    "landing.features.coverLetterGenerator.title": "Motivationsschreiben-Generator",
    "landing.features.coverLetterGenerator.description": "GPT-4o schreibt ein persönliches, vermieter-taugliches Schreiben, das menschlich klingt – nicht nach ChatGPT.",
    "landing.features.coverLetterGenerator.badge": "Mehrsprachig verfügbar",
    "landing.features.appointmentBooking.title": "Smart Terminbuchung",
    "landing.features.appointmentBooking.description": "Calendly-Integration verhindert Doppelbuchungen. Automatische Erinnerungen und ICS-Kalender-Einträge.",
    "landing.features.appointmentBooking.badge": "Echtzeit-Synchronisation",
    "landing.features.dossierBundle.title": "Top-3 Dossier-Bundle",
    "landing.features.dossierBundle.description": "Die drei besten Kandidaten werden automatisch als PDF/ZIP zusammengestellt – bereit für die Regie-Einreichung.",
    "landing.features.dossierBundle.badge": "Ein-Klick Export",
    "landing.features.decisionFeedback.title": "Entscheidungs-Feedback",
    "landing.features.decisionFeedback.description": "Vermieter und Kandidaten geben Rückmeldung über die finale Entscheidung. Voucher-System als Anreiz.",
    "landing.features.decisionFeedback.badge": "Voucher-Belohnung",
    "landing.pricing.title": "Transparent und fair",
    "landing.pricing.description": "Keine versteckten Kosten. Zahlung nur bei Erfolg.",
    "landing.pricing.basic.title": "Basis",
    "landing.pricing.basic.price": "Kostenlos",
    "landing.pricing.basic.subtitle": "Für erste Versuche",
    "landing.pricing.basic.feature1": "Smart Link erstellen",
    "landing.pricing.basic.feature2": "Bis zu 5 Bewerbungen",
    "landing.pricing.basic.feature3": "Basis-Dokumentvalidierung",
    "landing.pricing.basic.cta": "Jetzt starten",
    "landing.pricing.popularBadge": "Beliebt",
    "landing.pricing.premium.title": "Premium",
    "landing.pricing.premium.price": "CHF 49",
    "landing.pricing.premium.subtitle": "Pro Wohnungsinserat",
    "landing.pricing.premium.feature1": "Alles aus Basis",
    "landing.pricing.premium.feature2": "Unbegrenzte Bewerbungen",
    "landing.pricing.premium.feature3": "AI Mietvertrag-Parser",
    "landing.pricing.premium.feature4": "Premium AI-Validierung",
    "landing.pricing.premium.cta": "Premium wählen",
    "landing.pricing.regie.title": "Regie",
    "landing.pricing.regie.price": "Custom",
    "landing.pricing.regie.subtitle": "Für Verwaltungen",
    "landing.pricing.regie.feature1": "Alles aus Premium",
    "landing.pricing.regie.feature2": "API-Integration",
    "landing.pricing.regie.feature3": "White-Label Option",
    "landing.pricing.regie.cta": "Kontakt aufnehmen",
    "landing.paymentTrust.description": "Sichere Zahlung über Stripe. Ihre Daten werden verschlüsselt übertragen.",
    "landing.ctaSection.title": "Bereit für den modernsten Nachmieter-Prozess der Schweiz?",
    "landing.ctaSection.description": "Schliessen Sie sich bereits hunderten von zufriedenen Nutzern an und verwandeln Sie Ihren Nachmieter-Stress in einen reibungslosen Ablauf.",
    "landing.ctaSection.startCta": "Jetzt kostenlos starten",
    "landing.ctaSection.demoCta": "Demo ansehen",
    "landing.ctaSection.readyToUse": "Sofort einsatzbereit",
    "landing.ctaSection.noCreditCard": "Keine Kreditkarte",
    "landing.ctaSection.swissHosted": "Swiss-hosted",
    "landing.footer.description": "Die moderne Schweizer Plattform für nahtlose Nachmieter-Handovers. Rechtssicher, datenschutzkonform und benutzerfreundlich.",
    "landing.footer.product.title": "Produkt",
    "landing.footer.product.features": "Features",
    "landing.footer.product.pricing": "Preise",
    "landing.footer.product.demo": "Demo",
    "landing.footer.product.api": "API",
    "landing.footer.support.title": "Support",
    "landing.footer.support.helpCenter": "Hilfe-Center",
    "landing.footer.support.contact": "Kontakt",
    "landing.footer.support.status": "Status",
    "landing.footer.support.roadmap": "Roadmap",
    "landing.footer.legal.title": "Rechtliches",
    "landing.footer.legal.privacy": "Datenschutz",
    "landing.footer.legal.terms": "AGB",
    "landing.footer.legal.imprint": "Impressum",
    "landing.footer.legal.cookies": "Cookies",
    "landing.footer.copyright": "© 2024 MietLink AG. Alle Rechte vorbehalten.",
    "landing.footer.hostedInSwitzerland": "Hosted in Switzerland",
    "landing.footer.gdprCompliant": "GDPR Compliant",
    
    // Home dashboard
    "home.welcome": "Willkommen zurück",
    "home.dashboard": "Dashboard",
    "home.dashboard.description": "Verwalten Sie Ihre Immobilien und verfolgen Sie Bewerbungen in Echtzeit.",
    "home.newProperty": "Neue Wohnung",
    "home.newProperty.description": "Inserat erstellen",
    "home.properties": "Meine Wohnungen",
    "home.applications": "Bewerbungen",
    "home.applications.description": "Kandidaten verwalten",
    "home.documents": "Dokumente",
    "home.documents.description": "Verwalten & prüfen",
    "home.appointments": "Termine",
    "home.appointments.description": "Besichtigungen planen",
    "home.noProperties": "Noch keine Inserate",
    "home.noProperties.description": "Erstellen Sie Ihr erstes Wohnungsinserat und finden Sie automatisch den perfekten Nachmieter.",
    "home.createFirst": "Erstes Inserat erstellen",
    "home.property.rent": "Miete",
    "home.property.keys": "Schlüssel",
    "home.property.closed": "Geschlossen",
    "home.property.active": "Aktiv",
    "home.property.applications": "Bewerbungen",
    "home.property.views": "Aufrufe",
    "home.property.appointments": "Termine",
    "home.property.manage": "Verwalten",
    "home.property.share": "Teilen",
    "home.stats.title": "Statistiken",
    "home.stats.activeListings": "Aktive Inserate",
    "home.stats.totalApplications": "Bewerbungen gesamt",
    "home.stats.successRate": "Erfolgsquote",
    "home.recentActivity.title": "Letzte Aktivitäten",
    "home.recentActivity.noActivity": "Noch keine Aktivitäten",
    "home.tips.title": "💡 Tipp",
    "home.tips.description": "Laden Sie Fotos Ihrer Wohnung hoch, um 3x mehr qualifizierte Bewerbungen zu erhalten!",
    
    // Property setup
    "setup.contract.parsed": "Vertrag analysiert",
    "setup.contract.parsed.description": "Die wichtigsten Daten wurden automatisch extrahiert.",
    "setup.title": "Wohnung einrichten",
    "setup.subtitle": "Laden Sie Ihren Mietvertrag hoch oder geben Sie die Daten manuell ein",
    "setup.aiAnalysis": "AI-Analyse (Empfohlen)",
    "setup.aiDescription": "Mietvertrag hochladen - AI extrahiert automatisch alle wichtigen Daten",
    "setup.analyzingContract": "Vertrag wird analysiert...",
    "setup.supportedLanguages": "Unterstützt alle 5 Sprachen",
    "setup.manualEntry": "Manuelle Eingabe",
    "setup.manualEntryDesc": "Wohnungsdaten direkt eingeben",
    "setup.manualEntryButton": "Manuell eingeben",
    "setup.confirmData": "Wohnungsdaten bestätigen",
    "setup.confirmDataDesc": "Überprüfen und ergänzen Sie die extrahierten Daten",
    "setup.obligationsFound": "AI hat {count} Pflichten erkannt und automatisch extrahiert",
    "setup.locationHeading": "Standort & Grunddaten",
    "setup.fullAddress": "Vollständige Adresse",
    "setup.addressPlaceholder": "Musterstrasse 123, 8001 Zürich",
    "setup.rent": "Miete (CHF/Monat)",
    "setup.keyCount": "Anzahl Schlüssel",
    "setup.noticeMonths": "Kündigungsfrist (Monate)",
    "setup.earliestExit": "Frühestes Auszugsdatum",
    "setup.creating": "Wird erstellt...",
    "setup.createListing": "Inserat erstellen",
    "setup.created": "Ihr Inserat wurde erfolgreich erstellt.",
    "setup.parseError": "Vertrag konnte nicht analysiert werden: ",
    "setup.createError": "Inserat konnte nicht erstellt werden: ",
    "setup.step": "Schritt",
    "setup.of": "von",
    
    // Common
    "common.loading": "Lädt...",
    "common.error": "Ein Fehler ist aufgetreten",
    "common.success": "Erfolgreich",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.next": "Weiter",
    "common.back": "Zurück",
    "common.selectLanguage": "Sprache wählen",
  },
  
  en: {
    // Navigation
    "nav.login": "Sign In",
    "nav.getStarted": "Get Started",
    "nav.logout": "Sign Out",
    
    // Landing page
    "landing.hero.title": "Find your next tenant",
    "landing.hero.subtitle": "made easy",
    "landing.hero.description": "The first Swiss platform that transforms the painful tenant handover process into a simple, automated workflow. For all three parties.",
    "landing.stats.clicks": "Clicks to publish",
    "landing.stats.application": "Min. application",
    "landing.stats.acceptance": "Agency acceptance",
    "landing.cta.listProperty": "List property",
    "landing.cta.findProperty": "Find property",
    "landing.trust.noCreditCard": "No credit card required",
    "landing.trust.readyToUse": "Ready to use immediately",
    "landing.card.dossierValidated.title": "Dossier validated",
    "landing.card.dossierValidated.description": "Ready for agency submission",
    "landing.howItWorks.title": "How it works",
    "landing.howItWorks.description": "From first publication to final agency submission – all automated and legally compliant.",
    "landing.howItWorks.step1.title": "Create Smart Link",
    "landing.howItWorks.step1.description": "Upload your rental agreement or enter it manually. AI automatically extracts all important data.",
    "landing.howItWorks.step2.title": "Collect documents",
    "landing.howItWorks.step2.description": "Prospective tenants upload their documents once. AI automatically validates and classifies them.",
    "landing.howItWorks.step3.title": "Schedule viewings",
    "landing.howItWorks.step3.description": "Automatic appointment booking without double bookings. Calendly integration for seamless planning.",
    "landing.howItWorks.step4.title": "Top-3 Dossier",
    "landing.howItWorks.step4.description": "The best 3 candidates are automatically compiled as PDF/ZIP for agency submission.",
    "landing.features.title": "All Features at a Glance",
    "landing.features.description": "Developed for the Swiss legal landscape and local needs",
    "landing.features.parser.title": "AI Rental Agreement Parser",
    "landing.features.parser.description": "Upload your rental agreement and AI automatically extracts rent, notice period, number of keys, and creates a task list.",
    "landing.features.parser.badge": "Supports all 5 languages",
    "landing.features.documentWizard.title": "Document Wizard",
    "landing.features.documentWizard.description": "Upload documents once, AI validates immediately. Direct cantonal portal links for debt enforcement extract.",
    "landing.features.documentWizard.badge": "Swiss Data Protection",
    "landing.features.coverLetterGenerator.title": "Cover Letter Generator",
    "landing.features.coverLetterGenerator.description": "GPT-4o writes a personal, landlord-suitable letter that sounds human – not like ChatGPT.",
    "landing.features.coverLetterGenerator.badge": "Available in multiple languages",
    "landing.features.appointmentBooking.title": "Smart Appointment Booking",
    "landing.features.appointmentBooking.description": "Calendly integration prevents double bookings. Automatic reminders and ICS calendar entries.",
    "landing.features.appointmentBooking.badge": "Real-time synchronization",
    "landing.features.dossierBundle.title": "Top-3 Dossier Bundle",
    "landing.features.dossierBundle.description": "The three best candidates are automatically compiled as PDF/ZIP – ready for agency submission.",
    "landing.features.dossierBundle.badge": "One-Click Export",
    "landing.features.decisionFeedback.title": "Decision Feedback",
    "landing.features.decisionFeedback.description": "Landlords and candidates provide feedback on the final decision. Voucher system as an incentive.",
    "landing.features.decisionFeedback.badge": "Voucher Reward",
    "landing.pricing.title": "Transparent and fair",
    "landing.pricing.description": "No hidden costs. Payment only upon success.",
    "landing.pricing.basic.title": "Basic",
    "landing.pricing.basic.price": "Free",
    "landing.pricing.basic.subtitle": "For first attempts",
    "landing.pricing.basic.feature1": "Create Smart Link",
    "landing.pricing.basic.feature2": "Up to 5 applications",
    "landing.pricing.basic.feature3": "Basic document validation",
    "landing.pricing.basic.cta": "Get Started Now",
    "landing.pricing.popularBadge": "Popular",
    "landing.pricing.premium.title": "Premium",
    "landing.pricing.premium.price": "CHF 49",
    "landing.pricing.premium.subtitle": "Per property listing",
    "landing.pricing.premium.feature1": "All from Basic",
    "landing.pricing.premium.feature2": "Unlimited applications",
    "landing.pricing.premium.feature3": "AI Rental Agreement Parser",
    "landing.pricing.premium.feature4": "Premium AI Validation",
    "landing.pricing.premium.cta": "Choose Premium",
    "landing.pricing.regie.title": "Agency",
    "landing.pricing.regie.price": "Custom",
    "landing.pricing.regie.subtitle": "For administrations",
    "landing.pricing.regie.feature1": "All from Premium",
    "landing.pricing.regie.feature2": "API Integration",
    "landing.pricing.regie.feature3": "White-Label Option",
    "landing.pricing.regie.cta": "Contact Us",
    "landing.paymentTrust.description": "Secure payment via Stripe. Your data is transmitted encrypted.",
    "landing.ctaSection.title": "Ready for the most modern tenant handover process in Switzerland?",
    "landing.ctaSection.description": "Join hundreds of satisfied users and transform your tenant handover stress into a smooth process.",
    "landing.ctaSection.startCta": "Start for free now",
    "landing.ctaSection.demoCta": "View Demo",
    "landing.ctaSection.readyToUse": "Ready to use immediately",
    "landing.ctaSection.noCreditCard": "No credit card",
    "landing.ctaSection.swissHosted": "Swiss-hosted",
    "landing.footer.description": "The modern Swiss platform for seamless tenant handovers. Legally compliant, data protection compliant and user-friendly.",
    "landing.footer.product.title": "Product",
    "landing.footer.product.features": "Features",
    "landing.footer.product.pricing": "Pricing",
    "landing.footer.product.demo": "Demo",
    "landing.footer.product.api": "API",
    "landing.footer.support.title": "Support",
    "landing.footer.support.helpCenter": "Help Center",
    "landing.footer.support.contact": "Contact",
    "landing.footer.support.status": "Status",
    "landing.footer.support.roadmap": "Roadmap",
    "landing.footer.legal.title": "Legal",
    "landing.footer.legal.privacy": "Privacy Policy",
    "landing.footer.legal.terms": "Terms and Conditions",
    "landing.footer.legal.imprint": "Imprint",
    "landing.footer.legal.cookies": "Cookies",
    "landing.footer.copyright": "© 2024 MietLink AG. All rights reserved.",
    "landing.footer.hostedInSwitzerland": "Hosted in Switzerland",
    "landing.footer.gdprCompliant": "GDPR Compliant",
    
    // Home dashboard
    "home.welcome": "Welcome back",
    "home.dashboard": "Dashboard",
    "home.dashboard.description": "Manage your properties and track applications in real-time.",
    "home.newProperty": "New Property",
    "home.newProperty.description": "Create listing",
    "home.properties": "My Properties",
    "home.applications": "Applications",
    "home.applications.description": "Manage candidates",
    "home.documents": "Documents",
    "home.documents.description": "Manage & verify",
    "home.appointments": "Appointments",
    "home.appointments.description": "Schedule viewings",
    "home.noProperties": "No listings yet",
    "home.noProperties.description": "Create your first property listing and automatically find the perfect successor tenant.",
    "home.createFirst": "Create first listing",
    "home.property.rent": "Rent",
    "home.property.keys": "Keys",
    "home.property.closed": "Closed",
    "home.property.active": "Active",
    "home.property.applications": "Applications",
    "home.property.views": "Views",
    "home.property.appointments": "Appointments",
    "home.property.manage": "Manage",
    "home.property.share": "Share",
    "home.stats.title": "Statistics",
    "home.stats.activeListings": "Active Listings",
    "home.stats.totalApplications": "Total Applications",
    "home.stats.successRate": "Success Rate",
    "home.recentActivity.title": "Recent Activity",
    "home.recentActivity.noActivity": "No activities yet",
    "home.tips.title": "💡 Tip",
    "home.tips.description": "Upload photos of your apartment to get 3x more qualified applications!",
    
    // Property setup
    "setup.contract.parsed": "Contract analyzed",
    "setup.contract.parsed.description": "Key data has been automatically extracted.",
    "setup.title": "Set up property",
    "setup.subtitle": "Upload your rental contract or enter the data manually",
    "setup.aiAnalysis": "AI Analysis (Recommended)",
    "setup.aiDescription": "Upload contract - AI automatically extracts all important data",
    "setup.analyzingContract": "Analyzing contract...",
    "setup.supportedLanguages": "Supports all 5 languages",
    "setup.manualEntry": "Manual entry",
    "setup.manualEntryDesc": "Enter property data directly",
    "setup.manualEntryButton": "Enter manually",
    "setup.confirmData": "Confirm property data",
    "setup.confirmDataDesc": "Review and complete the extracted data",
    "setup.obligationsFound": "AI detected {count} obligations and extracted them automatically",
    "setup.locationHeading": "Location & basics",
    "setup.fullAddress": "Full address",
    "setup.addressPlaceholder": "Example Street 123, 8001 Zurich",
    "setup.rent": "Rent (CHF/month)",
    "setup.keyCount": "Number of keys",
    "setup.noticeMonths": "Notice period (months)",
    "setup.earliestExit": "Earliest move-out date",
    "setup.creating": "Creating...",
    "setup.createListing": "Create listing",
    "setup.created": "Your listing was created successfully.",
    "setup.parseError": "Contract could not be analyzed: ",
    "setup.createError": "Listing could not be created: ",
    "setup.step": "Step",
    "setup.of": "of",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.next": "Next",
    "common.back": "Back",
    "common.selectLanguage": "Select Language",
  },
  
  fr: {
    // Navigation
    "nav.login": "Se connecter",
    "nav.getStarted": "Commencer",
    "nav.logout": "Se déconnecter",
    
    // Landing page
    "landing.hero.title": "Trouvez votre prochain locataire",
    "landing.hero.subtitle": "facilement",
    "landing.hero.description": "La première plateforme suisse qui transforme le processus douloureux de transmission de bail en un flux de travail simple et automatisé. Pour les trois parties.",
    "landing.stats.clicks": "Clics pour publier",
    "landing.stats.application": "Min. candidature",
    "landing.stats.acceptance": "Acceptation agence",
    "landing.cta.listProperty": "Publier bien",
    "landing.cta.findProperty": "Trouver bien",
    "landing.trust.noCreditCard": "Pas de carte de crédit requise",
    "landing.trust.readyToUse": "Prêt à l'emploi immédiatement",
    "landing.card.dossierValidated.title": "Dossier validé",
    "landing.card.dossierValidated.description": "Prêt pour la soumission à l'agence",
    "landing.howItWorks.title": "Comment ça marche",
    "landing.howItWorks.description": "De la première publication à la soumission finale à l'agence – tout est automatisé et conforme à la loi.",
    "landing.howItWorks.step1.title": "Créer un lien intelligent",
    "landing.howItWorks.step1.description": "Téléchargez votre contrat de location ou saisissez-le manuellement. L'IA extrait automatiquement toutes les données importantes.",
    "landing.howItWorks.step2.title": "Collecter les documents",
    "landing.howItWorks.step2.description": "Les locataires potentiels téléchargent leurs documents une seule fois. L'IA les valide et les classe automatiquement.",
    "landing.howItWorks.step3.title": "Planifier les visites",
    "landing.howItWorks.step3.description": "Réservation automatique des rendez-vous sans double réservation. Intégration Calendly pour une planification transparente.",
    "landing.howItWorks.step4.title": "Dossier Top-3",
    "landing.howItWorks.step4.description": "Les 3 meilleurs candidats sont automatiquement compilés en PDF/ZIP pour la soumission à l'agence.",
    "landing.features.title": "Toutes les fonctionnalités en un coup d'œil",
    "landing.features.description": "Développé pour le paysage juridique suisse et les besoins locaux",
    "landing.features.parser.title": "Analyseur de contrat de location IA",
    "landing.features.parser.description": "Téléchargez votre contrat de location et l'IA extrait automatiquement le loyer, le délai de préavis, le nombre de clés et crée une liste de tâches.",
    "landing.features.parser.badge": "Prend en charge les 5 langues",
    "landing.features.documentWizard.title": "Assistant de documents",
    "landing.features.documentWizard.description": "Téléchargez les documents une seule fois, l'IA valide immédiatement. Liens directs vers les portails cantonaux pour l'extrait de poursuite.",
    "landing.features.documentWizard.badge": "Protection des données suisses",
    "landing.features.coverLetterGenerator.title": "Générateur de lettre de motivation",
    "landing.features.coverLetterGenerator.description": "GPT-4o rédige une lettre personnelle, adaptée aux propriétaires, qui semble humaine – pas comme ChatGPT.",
    "landing.features.coverLetterGenerator.badge": "Disponible en plusieurs langues",
    "landing.features.appointmentBooking.title": "Réservation de rendez-vous intelligente",
    "landing.features.appointmentBooking.description": "L'intégration Calendly empêche les doubles réservations. Rappels automatiques et entrées de calendrier ICS.",
    "landing.features.appointmentBooking.badge": "Synchronisation en temps réel",
    "landing.features.dossierBundle.title": "Pack Dossier Top-3",
    "landing.features.dossierBundle.description": "Les trois meilleurs candidats sont automatiquement compilés en PDF/ZIP – prêts pour la soumission à l'agence.",
    "landing.features.dossierBundle.badge": "Exportation en un clic",
    "landing.features.decisionFeedback.title": "Retour d'information sur la décision",
    "landing.features.decisionFeedback.description": "Les propriétaires et les candidats fournissent des commentaires sur la décision finale. Système de bons comme incitation.",
    "landing.features.decisionFeedback.badge": "Récompense par bon",
    "landing.pricing.title": "Transparent et juste",
    "landing.pricing.description": "Pas de coûts cachés. Paiement uniquement en cas de succès.",
    "landing.pricing.basic.title": "Basique",
    "landing.pricing.basic.price": "Gratuit",
    "landing.pricing.basic.subtitle": "Pour les premières tentatives",
    "landing.pricing.basic.feature1": "Créer un lien intelligent",
    "landing.pricing.basic.feature2": "Jusqu'à 5 candidatures",
    "landing.pricing.basic.feature3": "Validation de document de base",
    "landing.pricing.basic.cta": "Commencer maintenant",
    "landing.pricing.popularBadge": "Populaire",
    "landing.pricing.premium.title": "Premium",
    "landing.pricing.premium.price": "CHF 49",
    "landing.pricing.premium.subtitle": "Par annonce immobilière",
    "landing.pricing.premium.feature1": "Tout de Basique",
    "landing.pricing.premium.feature2": "Candidatures illimitées",
    "landing.pricing.premium.feature3": "Analyseur de contrat de location IA",
    "landing.pricing.premium.feature4": "Validation IA Premium",
    "landing.pricing.premium.cta": "Choisir Premium",
    "landing.pricing.regie.title": "Agence",
    "landing.pricing.regie.price": "Personnalisé",
    "landing.pricing.regie.subtitle": "Pour les administrations",
    "landing.pricing.regie.feature1": "Tout de Premium",
    "landing.pricing.regie.feature2": "Intégration API",
    "landing.pricing.regie.feature3": "Option marque blanche",
    "landing.pricing.regie.cta": "Nous contacter",
    "landing.paymentTrust.description": "Paiement sécurisé via Stripe. Vos données sont transmises cryptées.",
    "landing.ctaSection.title": "Prêt pour le processus de transmission de locataire le plus moderne de Suisse ?",
    "landing.ctaSection.description": "Rejoignez des centaines d'utilisateurs satisfaits et transformez votre stress de transmission de locataire en un processus fluide.",
    "landing.ctaSection.startCta": "Commencer gratuitement maintenant",
    "landing.ctaSection.demoCta": "Voir la démo",
    "landing.ctaSection.readyToUse": "Prêt à l'emploi immédiatement",
    "landing.ctaSection.noCreditCard": "Pas de carte de crédit",
    "landing.ctaSection.swissHosted": "Hébergé en Suisse",
    "landing.footer.description": "La plateforme suisse moderne pour des transmissions de locataires fluides. Conforme à la loi, à la protection des données et conviviale.",
    "landing.footer.product.title": "Produit",
    "landing.footer.product.features": "Fonctionnalités",
    "landing.footer.product.pricing": "Tarifs",
    "landing.footer.product.demo": "Démo",
    "landing.footer.product.api": "API",
    "landing.footer.support.title": "Support",
    "landing.footer.support.helpCenter": "Centre d'aide",
    "landing.footer.support.contact": "Contact",
    "landing.footer.support.status": "Statut",
    "landing.footer.support.roadmap": "Feuille de route",
    "landing.footer.legal.title": "Mentions légales",
    "landing.footer.legal.privacy": "Politique de confidentialité",
    "landing.footer.legal.terms": "Conditions générales",
    "landing.footer.legal.imprint": "Mentions légales",
    "landing.footer.legal.cookies": "Cookies",
    "landing.footer.copyright": "© 2024 MietLink AG. Tous droits réservés.",
    "landing.footer.hostedInSwitzerland": "Hébergé en Suisse",
    "landing.footer.gdprCompliant": "Conforme au RGPD",

    // Home dashboard
    "home.welcome": "Bienvenue",
    "home.dashboard": "Tableau de bord",
    "home.dashboard.description": "Gérez vos biens et suivez les candidatures en temps réel.",
    "home.newProperty": "Nouveau bien",
    "home.newProperty.description": "Créer annonce",
    "home.properties": "Mes biens",
    "home.applications": "Candidatures",
    "home.applications.description": "Gérer candidats",
    "home.documents": "Documents",
    "home.documents.description": "Gérer & vérifier",
    "home.appointments": "Rendez-vous",
    "home.appointments.description": "Planifier visites",
    "home.noProperties": "Aucune annonce encore",
    "home.noProperties.description": "Créez votre première annonce immobilière et trouvez automatiquement le locataire successeur parfait.",
    "home.createFirst": "Créer première annonce",
    "home.property.rent": "Loyer",
    "home.property.keys": "Clés",
    "home.property.closed": "Fermé",
    "home.property.active": "Actif",
    "home.property.applications": "Candidatures",
    "home.property.views": "Vues",
    "home.property.appointments": "Rendez-vous",
    "home.property.manage": "Gérer",
    "home.property.share": "Partager",
    "home.stats.title": "Statistiques",
    "home.stats.activeListings": "Annonces actives",
    "home.stats.totalApplications": "Total des candidatures",
    "home.stats.successRate": "Taux de réussite",
    "home.recentActivity.title": "Activités récentes",
    "home.recentActivity.noActivity": "Aucune activité pour l'instant",
    "home.tips.title": "💡 Astuce",
    "home.tips.description": "Téléchargez des photos de votre appartement pour obtenir 3x plus de candidatures qualifiées !",

    // Property setup
    "setup.contract.parsed": "Contrat analysé",
    "setup.contract.parsed.description": "Les données clés ont été extraites automatiquement.",
    "setup.title": "Configurer le logement",
    "setup.subtitle": "Téléchargez votre contrat de location ou saisissez les données manuellement",
    "setup.aiAnalysis": "Analyse AI (recommandé)",
    "setup.aiDescription": "Télécharger le contrat - l'IA extrait automatiquement les données clés",
    "setup.analyzingContract": "Analyse du contrat...",
    "setup.supportedLanguages": "Prend en charge les 5 langues",
    "setup.manualEntry": "Saisie manuelle",
    "setup.manualEntryDesc": "Saisir les données du logement directement",
    "setup.manualEntryButton": "Saisie manuelle",
    "setup.confirmData": "Confirmer les données du logement",
    "setup.confirmDataDesc": "Vérifiez et complétez les données extraites",
    "setup.obligationsFound": "L'IA a détecté {count} obligations et les a extraites automatiquement",
    "setup.locationHeading": "Emplacement & infos de base",
    "setup.fullAddress": "Adresse complète",
    "setup.addressPlaceholder": "Rue Exemple 123, 8001 Zurich",
    "setup.rent": "Loyer (CHF/mois)",
    "setup.keyCount": "Nombre de clés",
    "setup.noticeMonths": "Délai de résiliation (mois)",
    "setup.earliestExit": "Date de départ la plus proche",
    "setup.creating": "Création en cours...",
    "setup.createListing": "Créer l'annonce",
    "setup.created": "Votre annonce a été créée avec succès.",
    "setup.parseError": "Le contrat n'a pas pu être analysé : ",
    "setup.createError": "L'annonce n'a pas pu être créée : ",
    "setup.step": "Étape",
    "setup.of": "sur",

    // Common
    "common.loading": "Chargement...",
    "common.error": "Une erreur s'est produite",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Enregistrer",
    "common.next": "Suivant",
    "common.back": "Retour",
    "common.selectLanguage": "Choisir la langue",
  },
  
  it: {
    // Navigation
    "nav.login": "Accedi",
    "nav.getStarted": "Inizia",
    "nav.logout": "Esci",
    
    // Landing page
    "landing.hero.title": "Trova il tuo prossimo inquilino",
    "landing.hero.subtitle": "facilmente",
    "landing.hero.description": "La prima piattaforma svizzera che trasforma il doloroso processo di consegna dell'affitto in un flusso di lavoro semplice e automatizzato. Per tutte e tre le parti.",
    "landing.stats.clicks": "Clic per pubblicare",
    "landing.stats.application": "Min. candidatura",
    "landing.stats.acceptance": "Accettazione agenzia",
    "landing.cta.listProperty": "Pubblica immobile",
    "landing.cta.findProperty": "Trova immobile",
    "landing.trust.noCreditCard": "Nessuna carta di credito richiesta",
    "landing.trust.readyToUse": "Pronto all'uso immediatamente",
    "landing.card.dossierValidated.title": "Dossier convalidato",
    "landing.card.dossierValidated.description": "Pronto per la presentazione all'agenzia",
    "landing.howItWorks.title": "Come funziona",
    "landing.howItWorks.description": "Dalla prima pubblicazione alla presentazione finale all'agenzia – tutto automatizzato e legalmente conforme.",
    "landing.howItWorks.step1.title": "Crea Smart Link",
    "landing.howItWorks.step1.description": "Carica il tuo contratto di locazione o inseriscilo manualmente. L'IA estrae automaticamente tutti i dati importanti.",
    "landing.howItWorks.step2.title": "Raccogli documenti",
    "landing.howItWorks.step2.description": "I potenziali inquilini caricano i loro documenti una sola volta. L'IA li convalida e li classifica automaticamente.",
    "landing.howItWorks.step3.title": "Pianifica le visite",
    "landing.howItWorks.step3.description": "Prenotazione automatica degli appuntamenti senza doppie prenotazioni. Integrazione Calendly per una pianificazione senza interruzioni.",
    "landing.howItWorks.step4.title": "Dossier Top-3",
    "landing.howItWorks.step4.description": "I 3 migliori candidati vengono automaticamente compilati come PDF/ZIP per la presentazione all'agenzia.",
    "landing.features.title": "Tutte le funzionalità a colpo d'occhio",
    "landing.features.description": "Sviluppato per il panorama giuridico svizzero e le esigenze locali",
    "landing.features.parser.title": "Parser AI per contratti di locazione",
    "landing.features.parser.description": "Carica il tuo contratto di locazione e l'IA estrae automaticamente l'affitto, il periodo di preavviso, il numero de chiavi e crea un elenco di attività.",
    "landing.features.parser.badge": "Supporta tutte le 5 lingue",
    "landing.features.documentWizard.title": "Wizard Documenti",
    "landing.features.documentWizard.description": "Carica i documenti una sola volta, l'IA convalida immediatamente. Collegamenti diretti ai portali cantonali per l'estratto esecutivo.",
    "landing.features.documentWizard.badge": "Protezione dei dati svizzera",
    "landing.features.coverLetterGenerator.title": "Generatore di lettere di presentazione",
    "landing.features.coverLetterGenerator.description": "GPT-4o escribe una lettera personale, adatta ai proprietari, che suona umana – non come ChatGPT.",
    "landing.features.coverLetterGenerator.badge": "Disponibile in più lingue",
    "landing.features.appointmentBooking.title": "Prenotazione appuntamenti intelligente",
    "landing.features.appointmentBooking.description": "L'integrazione Calendly previene le doppie prenotazioni. Promemoria automatici e voci di calendario ICS.",
    "landing.features.appointmentBooking.badge": "Sincronizzazione in tempo reale",
    "landing.features.dossierBundle.title": "Pacchetto Dossier Top-3",
    "landing.features.dossierBundle.description": "I tre migliori candidati vengono automaticamente compilati come PDF/ZIP – pronti per la presentazione all'agenzia.",
    "landing.features.dossierBundle.badge": "Esportazione con un clic",
    "landing.features.decisionFeedback.title": "Feedback sulla decisione",
    "landing.features.decisionFeedback.description": "Proprietari e candidati forniscono feedback sulla decisione finale. Sistema di voucher come incentivo.",
    "landing.features.decisionFeedback.badge": "Ricompensa voucher",
    "landing.pricing.title": "Trasparente ed equo",
    "landing.pricing.description": "Nessun costo nascosto. Pagamento solo a successo.",
    "landing.pricing.basic.title": "Base",
    "landing.pricing.basic.price": "Gratuito",
    "landing.pricing.basic.subtitle": "Per i primi tentativi",
    "landing.pricing.basic.feature1": "Crea Smart Link",
    "landing.pricing.basic.feature2": "Fino a 5 candidature",
    "landing.pricing.basic.feature3": "Validazione documenti di base",
    "landing.pricing.basic.cta": "Inizia ora",
    "landing.pricing.popularBadge": "Popolare",
    "landing.pricing.premium.title": "Premium",
    "landing.pricing.premium.price": "CHF 49",
    "landing.pricing.premium.subtitle": "Per annuncio immobiliare",
    "landing.pricing.premium.feature1": "Tutto da Base",
    "landing.pricing.premium.feature2": "Candidature illimitate",
    "landing.pricing.premium.feature3": "Parser AI per contratti di locazione",
    "landing.pricing.premium.feature4": "Validazione AI Premium",
    "landing.pricing.premium.cta": "Scegli Premium",
    "landing.pricing.regie.title": "Agenzia",
    "landing.pricing.regie.price": "Personalizzato",
    "landing.pricing.regie.subtitle": "Per le amministrazioni",
    "landing.pricing.regie.feature1": "Tutto da Premium",
    "landing.pricing.regie.feature2": "Integrazione API",
    "landing.pricing.regie.feature3": "Opzione White-Label",
    "landing.pricing.regie.cta": "Contattaci",
    "landing.paymentTrust.description": "Pagamento sicuro tramite Stripe. I tuoi dati vengono trasmessi crittografati.",
    "landing.ctaSection.title": "Pronto per el proceso de entrega del inquilino más moderno de Suiza?",
    "landing.ctaSection.description": "Unisciti a centinaia de utenti soddisfatti e trasforma lo stress della consegna dell'inquilino in un processo fluido.",
    "landing.ctaSection.startCta": "Inicia ora gratuitamente",
    "landing.ctaSection.demoCta": "Mira la demo",
    "landing.ctaSection.readyToUse": "Listo para usar inmediatamente",
    "landing.ctaSection.noCreditCard": "Nessuna carta di credito",
    "landing.ctaSection.swissHosted": "Ospitato in Svizzera",
    "landing.footer.description": "La moderna piattaforma svizzera per consegne di inquilini senza interruzioni. Legalmente conforme, conforme alla protezione dei dati e facile da usare.",
    "landing.footer.product.title": "Prodotto",
    "landing.footer.product.features": "Funzionalità",
    "landing.footer.product.pricing": "Prezzi",
    "landing.footer.product.demo": "Demo",
    "landing.footer.product.api": "API",
    "landing.footer.support.title": "Supporto",
    "landing.footer.support.helpCenter": "Centro assistenza",
    "landing.footer.support.contact": "Contatto",
    "landing.footer.support.status": "Stato",
    "landing.footer.support.roadmap": "Roadmap",
    "landing.footer.legal.title": "Legale",
    "landing.footer.legal.privacy": "Informativa sulla privacy",
    "landing.footer.legal.terms": "Termini e condizioni",
    "landing.footer.legal.imprint": "Impronta",
    "landing.footer.legal.cookies": "Cookie",
    "landing.footer.copyright": "© 2024 MietLink AG. Tutti i diritti riservati.",
    "landing.footer.hostedInSwitzerland": "Ospitato in Svizzera",
    "landing.footer.gdprCompliant": "Conforme al GDPR",

    // Home dashboard
    "home.welcome": "Bentornato",
    "home.dashboard": "Dashboard",
    "home.dashboard.description": "Gestisci le tue proprietà e monitora le candidature in tempo reale.",
    "home.newProperty": "Nuova proprietà",
    "home.newProperty.description": "Crea annuncio",
    "home.properties": "Le mie proprietà",
    "home.applications": "Candidature",
    "home.applications.description": "Gestisci i candidati",
    "home.documents": "Documenti",
    "home.documents.description": "Gestisci e verifica",
    "home.appointments": "Appuntamenti",
    "home.appointments.description": "Programma visite",
    "home.noProperties": "Nessun annuncio ancora",
    "home.noProperties.description": "Crea il tuo primo annuncio e trova automaticamente il perfetto inquilino sostituto.",
    "home.createFirst": "Crea il primo annuncio",
    "home.property.rent": "Affitto",
    "home.property.keys": "Chiavi",
    "home.property.closed": "Chiuso",
    "home.property.active": "Attivo",
    "home.property.applications": "Candidature",
    "home.property.views": "Visite",
    "home.property.appointments": "Appuntamenti",
    "home.property.manage": "Gestisci",
    "home.property.share": "Condividi",
    "home.stats.title": "Statistiche",
    "home.stats.activeListings": "Annunci attivi",
    "home.stats.totalApplications": "Candidature totali",
    "home.stats.successRate": "Tasso di successo",
    "home.recentActivity.title": "Attività recenti",
    "home.recentActivity.noActivity": "Nessuna attività",
    "home.tips.title": "💡 Consiglio",
    "home.tips.description": "Carica foto del tuo appartamento per ricevere 3x più candidature qualificate!",

    // Property setup
    "setup.contract.parsed": "Contratto analizzato",
    "setup.contract.parsed.description": "I dati principali sono stati estratti automaticamente.",
    "setup.title": "Configura la proprietà",
    "setup.subtitle": "Carica il contratto di locazione o inserisci i dati manualmente",
    "setup.aiAnalysis": "Analisi AI (consigliata)",
    "setup.aiDescription": "Carica il contratto - l'AI estrae automaticamente tutti i dati importanti",
    "setup.analyzingContract": "Analisi del contratto...",
    "setup.supportedLanguages": "Supporta tutte e 5 le lingue",
    "setup.manualEntry": "Inserimento manuale",
    "setup.manualEntryDesc": "Inserisci direttamente i dati della proprietà",
    "setup.manualEntryButton": "Inserisci manualmente",
    "setup.confirmData": "Conferma i dati della proprietà",
    "setup.confirmDataDesc": "Verifica e completa i dati estratti",
    "setup.obligationsFound": "L'AI ha rilevato {count} obblighi ed è stata estratta automaticamente",
    "setup.locationHeading": "Posizione e dati base",
    "setup.fullAddress": "Indirizzo completo",
    "setup.addressPlaceholder": "Via Esempio 123, 8001 Zurigo",
    "setup.rent": "Affitto (CHF/mese)",
    "setup.keyCount": "Numero di chiavi",
    "setup.noticeMonths": "Preavviso (mesi)",
    "setup.earliestExit": "Data di uscita più vicina",
    "setup.creating": "Creazione in corso...",
    "setup.createListing": "Crea annuncio",
    "setup.created": "Il tuo annuncio è stato creato con successo.",
    "setup.parseError": "Il contratto non può essere analizzato: ",
    "setup.createError": "Impossibile creare l'annuncio: ",
    "setup.step": "Passo",
    "setup.of": "di",

    // Common
    "common.loading": "Caricamento...",
    "common.error": "Si è verificato un errore",
    "common.success": "Operazione riuscita",
    "common.cancel": "Annulla",
    "common.save": "Salva",
    "common.next": "Avanti",
    "common.back": "Indietro",
    "common.selectLanguage": "Seleziona lingua",
  },
  
  es: {
    // Navigation
    "nav.login": "Iniciar sesión",
    "nav.getStarted": "Comenzar",
    "nav.logout": "Cerrar sesión",
    
    // Landing page
    "landing.hero.title": "Encuentra tu próximo inquilino",
    "landing.hero.subtitle": "fácilmente",
    "landing.hero.description": "La primera plataforma suiza que transforma el doloroso proceso de traspaso de alquiler en un flujo de trabajo simple y automatizado. Para las tres partes.",
    "landing.stats.clicks": "Clics para publicar",
    "landing.stats.application": "Min. solicitud",
    "landing.stats.acceptance": "Aceptación agencia",
    "landing.cta.listProperty": "Publicar propiedad",
    "landing.cta.findProperty": "Buscar propiedad",
    "landing.trust.noCreditCard": "No se requiere tarjeta de crédito",
    "landing.trust.readyToUse": "Listo para usar inmediatamente",
    "landing.card.dossierValidated.title": "Dossier validado",
    "landing.card.dossierValidated.description": "Listo para la presentación a la agencia",
    "landing.howItWorks.title": "Cómo funciona",
    "landing.howItWorks.description": "Desde la primera publicación hasta la presentación final a la agencia – todo automatizado y legalmente conforme.",
    "landing.howItWorks.step1.title": "Crear enlace inteligente",
    "landing.howItWorks.step1.description": "Sube tu contrato de alquiler o introdúcelo manualmente. La IA extrae automáticamente todos los datos importantes.",
    "landing.howItWorks.step2.title": "Recopilar documentos",
    "landing.howItWorks.step2.description": "Los posibles inquilinos suben sus documentos una sola vez. La IA los valida y clasifica automáticamente.",
    "landing.howItWorks.step3.title": "Programar visitas",
    "landing.howItWorks.step3.description": "Reserva automática de citas sin duplicidades. Integración de Calendly para una planificación perfecta.",
    "landing.howItWorks.step4.title": "Dossier Top-3",
    "landing.howItWorks.step4.description": "Los 3 mejores candidatos se compilan automáticamente como PDF/ZIP para la presentación a la agencia.",
    "landing.features.title": "Todas las características de un vistazo",
    "landing.features.description": "Desarrollado para el marco legal suizo y las necesidades locales",
    "landing.features.parser.title": "Analizador de contratos de alquiler con IA",
    "landing.features.parser.description": "Sube tu contrato de alquiler y la IA extrae automáticamente el alquiler, el período de preaviso, el número de llaves y crea una lista de tareas.",
    "landing.features.parser.badge": "Soporta los 5 idiomas",
    "landing.features.documentWizard.title": "Asistente de documentos",
    "landing.features.documentWizard.description": "Sube documentos una sola vez, la IA valida inmediatamente. Enlaces directos a los portales cantonales para el extracto de ejecución.",
    "landing.features.documentWizard.badge": "Protección de datos suiza",
    "landing.features.coverLetterGenerator.title": "Generador de carta de presentación",
    "landing.features.coverLetterGenerator.description": "GPT-4o escribe una carta personal, adecuada para propietarios, que suena humana – no como ChatGPT.",
    "landing.features.coverLetterGenerator.badge": "Disponible en varios idiomas",
    "landing.features.appointmentBooking.title": "Reserva de citas inteligente",
    "landing.features.appointmentBooking.description": "La integración de Calendly evita las reservas dobles. Recordatorios automáticos y entradas de calendario ICS.",
    "landing.features.appointmentBooking.badge": "Sincronización en tiempo real",
    "landing.features.dossierBundle.title": "Paquete Dossier Top-3",
    "landing.features.dossierBundle.description": "Los tres mejores candidatos se compilan automáticamente como PDF/ZIP – listos para la presentación a la agencia.",
    "landing.features.dossierBundle.badge": "Exportación con un clic",
    "landing.features.decisionFeedback.title": "Comentarios sobre la decisión",
    "landing.features.decisionFeedback.description": "Los propietarios y los candidatos proporcionan comentarios sobre la decisión final. Sistema de vales como incentivo.",
    "landing.features.decisionFeedback.badge": "Recompensa con vale",
    "landing.pricing.title": "Transparente y justo",
    "landing.pricing.description": "Sin costes ocultos. Pago solo al éxito.",
    "landing.pricing.basic.title": "Básico",
    "landing.pricing.basic.price": "Gratis",
    "landing.pricing.basic.subtitle": "Para los primeros intentos",
    "landing.pricing.basic.feature1": "Crear enlace inteligente",
    "landing.pricing.basic.feature2": "Hasta 5 solicitudes",
    "landing.pricing.basic.feature3": "Validación básica de documentos",
    "landing.pricing.basic.cta": "Empezar ahora",
    "landing.pricing.popularBadge": "Popular",
    "landing.pricing.premium.title": "Premium",
    "landing.pricing.premium.price": "CHF 49",
    "landing.pricing.premium.subtitle": "Por anuncio de propiedad",
    "landing.pricing.premium.feature1": "Todo lo de Básico",
    "landing.pricing.premium.feature2": "Solicitudes ilimitadas",
    "landing.pricing.premium.feature3": "Analizador de contratos de alquiler con IA",
    "landing.pricing.premium.feature4": "Validación Premium con IA",
    "landing.pricing.premium.cta": "Elegir Premium",
    "landing.pricing.regie.title": "Agencia",
    "landing.pricing.regie.price": "Personalizado",
    "landing.pricing.regie.subtitle": "Para administraciones",
    "landing.pricing.regie.feature1": "Todo lo de Premium",
    "landing.pricing.regie.feature2": "Integración API",
    "landing.pricing.regie.feature3": "Opción de marca blanca",
    "landing.pricing.regie.cta": "Contactar",
    "landing.paymentTrust.description": "Pago seguro a través de Stripe. Tus datos se transmiten cifrados.",
    "landing.ctaSection.title": "¿Listo para el proceso de traspaso de inquilinos más moderno de Suiza?",
    "landing.ctaSection.description": "Únete a cientos de usuarios satisfechos y transforma el estrés del traspaso de inquilinos en un proceso fluido.",
    "landing.ctaSection.startCta": "Empezar gratis ahora",
    "landing.ctaSection.demoCta": "Ver demo",
    "landing.ctaSection.readyToUse": "Listo para usar inmediatamente",
    "landing.ctaSection.noCreditCard": "Sin tarjeta de crédito",
    "landing.ctaSection.swissHosted": "Alojado en Suiza",
    "landing.footer.description": "La moderna plataforma suiza para traspasos de inquilinos sin problemas. Legalmente conforme, compatible con la protección de datos y fácil de usar.",
    "landing.footer.product.title": "Producto",
    "landing.footer.product.features": "Características",
    "landing.footer.product.pricing": "Precios",
    "landing.footer.product.demo": "Demo",
    "landing.footer.product.api": "API",
    "landing.footer.support.title": "Soporte",
    "landing.footer.support.helpCenter": "Centro de ayuda",
    "landing.footer.support.contact": "Contacto",
    "landing.footer.support.status": "Estado",
    "landing.footer.support.roadmap": "Hoja de ruta",
    "landing.footer.legal.title": "Legal",
    "landing.footer.legal.privacy": "Política de privacidad",
    "landing.footer.legal.terms": "Términos y condiciones",
    "landing.footer.legal.imprint": "Aviso legal",
    "landing.footer.legal.cookies": "Cookies",
    "landing.footer.copyright": "© 2024 MietLink AG. Todos los derechos reservados.",
    "landing.footer.hostedInSwitzerland": "Alojado en Suiza",
    "landing.footer.gdprCompliant": "Cumple con GDPR",

    // Home dashboard
    "home.welcome": "Bienvenido de nuevo",
    "home.dashboard": "Panel de control",
    "home.dashboard.description": "Administra tus propiedades y sigue las solicitudes en tiempo real.",
    "home.newProperty": "Nueva propiedad",
    "home.newProperty.description": "Crear anuncio",
    "home.properties": "Mis propiedades",
    "home.applications": "Solicitudes",
    "home.applications.description": "Gestionar candidatos",
    "home.documents": "Documentos",
    "home.documents.description": "Gestionar y verificar",
    "home.appointments": "Citas",
    "home.appointments.description": "Programar visitas",
    "home.noProperties": "Aún sin anuncios",
    "home.noProperties.description": "Crea tu primer anuncio de propiedad y encuentra automáticamente al inquilino sucesor perfecto.",
    "home.createFirst": "Crear primer anuncio",
    "home.property.rent": "Alquiler",
    "home.property.keys": "Llaves",
    "home.property.closed": "Cerrado",
    "home.property.active": "Activo",
    "home.property.applications": "Solicitudes",
    "home.property.views": "Vistas",
    "home.property.appointments": "Citas",
    "home.property.manage": "Gestionar",
    "home.property.share": "Compartir",
    "home.stats.title": "Estadísticas",
    "home.stats.activeListings": "Anuncios activos",
    "home.stats.totalApplications": "Solicitudes totales",
    "home.stats.successRate": "Tasa de éxito",
    "home.recentActivity.title": "Actividad reciente",
    "home.recentActivity.noActivity": "Sin actividad aún",
    "home.tips.title": "💡 Consejo",
    "home.tips.description": "¡Sube fotos de tu apartamento para obtener 3x más solicitudes calificadas!",

    // Property setup
    "setup.contract.parsed": "Contrato analizado",
    "setup.contract.parsed.description": "Los datos clave se han extraído automáticamente.",
    "setup.title": "Configurar propiedad",
    "setup.subtitle": "Sube tu contrato de alquiler o ingresa los datos manualmente",
    "setup.aiAnalysis": "Análisis con IA (recomendado)",
    "setup.aiDescription": "Sube el contrato: la IA extrae automáticamente todos los datos importantes",
    "setup.analyzingContract": "Analizando contrato...",
    "setup.supportedLanguages": "Soporta los 5 idiomas",
    "setup.manualEntry": "Ingreso manual",
    "setup.manualEntryDesc": "Ingresa directamente los datos de la propiedad",
    "setup.manualEntryButton": "Ingresar manualmente",
    "setup.confirmData": "Confirmar datos de la propiedad",
    "setup.confirmDataDesc": "Revisa y completa los datos extraídos",
    "setup.obligationsFound": "La IA detectó {count} obligaciones y las extrajo automáticamente",
    "setup.locationHeading": "Ubicación y datos básicos",
    "setup.fullAddress": "Dirección completa",
    "setup.addressPlaceholder": "Calle Ejemplo 123, 8001 Zúrich",
    "setup.rent": "Alquiler (CHF/mes)",
    "setup.keyCount": "Número de llaves",
    "setup.noticeMonths": "Plazo de aviso (meses)",
    "setup.earliestExit": "Fecha de salida más temprana",
    "setup.creating": "Creando...",
    "setup.createListing": "Crear anuncio",
    "setup.created": "Tu anuncio se creó correctamente.",
    "setup.parseError": "No se pudo analizar el contrato: ",
    "setup.createError": "No se pudo crear el anuncio: ",
    "setup.step": "Paso",
    "setup.of": "de",

    // Common
    "common.loading": "Cargando...",
    "common.error": "Ocurrió un error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.next": "Siguiente",
    "common.back": "Atrás",
    "common.selectLanguage": "Seleccionar idioma",
  }
};

export function createLanguageSystem() {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("mietlink-language") as Language;
    if (savedLanguage && ["de", "fr", "it", "en", "es"].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("mietlink-language", lang);
  };

  const t = (
    key: string,
    vars: Record<string, string | number> = {}
  ): string => {
    const template = (translations[language] as any)?.[key] || key;
    return Object.keys(vars).reduce(
      (str, varKey) => str.replace(`{${varKey}}`, String(vars[varKey])),
      template
    );
  };

  return {
    language,
    setLanguage,
    t,
  };
}